DROP TABLE IF EXISTS CourseCategories CASCADE;

DROP TABLE IF EXISTS Courses CASCADE;

DROP TABLE IF EXISTS ProjectCategories CASCADE;

DROP TABLE IF EXISTS StudentProjectApplications;

DROP TABLE IF EXISTS Projects CASCADE;

DROP TABLE IF EXISTS ApplyStatuses CASCADE;

DROP TABLE IF EXISTS Designations CASCADE;

DROP TABLE IF EXISTS Categories CASCADE;

DROP TABLE IF EXISTS Students CASCADE;

DROP TABLE IF EXISTS Users CASCADE;

DROP TABLE IF EXISTS Majors CASCADE;

DROP TABLE IF EXISTS Years CASCADE;
